"""Add payment model

Revision ID: 3ff72ac93e47
Revises: d1b54cd24395
Create Date: 2025-06-30 01:54:55.574700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ff72ac93e47'
down_revision = 'd1b54cd24395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expense_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('method', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('payment_ibfk_1')),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], name=op.f('payment_ibfk_2')),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], name=op.f('payment_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('payments')
    # ### end Alembic commands ###
